// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIkXKF6L6V4LSBlk3xXhV-hhLRCrQSk4',
    appId: '1:107809960694:web:f0511e1a2377bb1dd8f2d7',
    messagingSenderId: '107809960694',
    projectId: 'ecommapp-1eb22',
    authDomain: 'ecommapp-1eb22.firebaseapp.com',
    storageBucket: 'ecommapp-1eb22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaNRdhzL_mM8TXFa29VlngrzDGcgyH8Xk',
    appId: '1:107809960694:android:57ee7d16bd65822fd8f2d7',
    messagingSenderId: '107809960694',
    projectId: 'ecommapp-1eb22',
    storageBucket: 'ecommapp-1eb22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxEs7BT42Z-9aIxBWOjVtQxixNrQw5Lo',
    appId: '1:107809960694:ios:b614cb1b8e055604d8f2d7',
    messagingSenderId: '107809960694',
    projectId: 'ecommapp-1eb22',
    storageBucket: 'ecommapp-1eb22.appspot.com',
    androidClientId: '107809960694-oepf1tj8a2sm1humfe84qko02bo7b8r4.apps.googleusercontent.com',
    iosClientId: '107809960694-uk7bopk9e9ao4l2dk03jp5gl0f6d6jhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
